plugins {
    id 'com.android.application'
}

android {
    namespace 'com.local.o2test'
    compileSdk 34

    defaultConfig {
        applicationId "com.local.o2test"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
        // Задаем базовое имя для скомпилированного APK файла
        setProperty("archivesBaseName", "o2test")

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    // Основные зависимости AndroidX и UI
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    // Библиотека графиков MPAndroidChart
    implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'
}
